[package]
name = "icmp-pinger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cookie-factory = "0.3.2"
nom = "7.1.3"
socket2 = "0.5"
